/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          bg: "#0D1117",
          paper: "#161B22",
          nav: "#0F2D5E",
          border: "#30363D",
          grid: "#21262D",
        },
        brand: {
          blue: "#1D4ED8",
          green: "#16A34A",
          red: "#DC2626",
          amber: "#D97706",
          text: "#E6EDF3",
          muted: "#7D8590",
        },
        "primary-fixed-dim": "#a2c9ff",
        "primary": "#a2c9ff",
        "tertiary": "#ffba42",
        "on-background": "#dfe2eb",
        "secondary-container": "#2e4869",
        "on-primary": "#00315c",
        "surface": "#10141a",
        "on-secondary-fixed": "#001c38",
        "on-tertiary-container": "#4f3400",
        "surface-container-high": "#262a31",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004882",
        "tertiary-fixed-dim": "#ffba42",
        "inverse-surface": "#dfe2eb",
        "on-tertiary-fixed-variant": "#614000",
        "primary-fixed": "#d3e4ff",
        "primary-container": "#58a6ff",
        "on-tertiary": "#432c00",
        "background": "#10141a",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#0060aa",
        "on-surface-variant": "#c0c7d4",
        "on-secondary-container": "#9db7dd",
        "outline-variant": "#414752",
        "surface-container": "#1c2026",
        "on-secondary-fixed-variant": "#2e4869",
        "surface-dim": "#10141a",
        "outline": "#8b919d",
        "secondary-fixed-dim": "#aec8ef",
        "secondary-fixed": "#d3e4ff",
        "tertiary-container": "#da9600",
        "on-primary-fixed": "#001c38",
        "tertiary-fixed": "#ffddaf",
        "on-surface": "#dfe2eb",
        "surface-container-highest": "#31353c",
        "surface-container-low": "#181c22",
        "surface-variant": "#31353c",
        "surface-container-lowest": "#0a0e14",
        "on-primary-container": "#003a6b",
        "surface-bright": "#353940",
        "inverse-on-surface": "#2d3137",
        "error": "#ffb4ab",
        "on-secondary": "#163151",
        "secondary": "#aec8ef",
        "surface-tint": "#a2c9ff",
        "on-error": "#690005",
        "on-tertiary-fixed": "#281800"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"]
      }
    },
  },
  plugins: [],
}
